/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MockFileItem: typeof import('./components/mock/MockFileItem.vue')['default']
    MockMethodItem: typeof import('./components/mock/MockMethodItem.vue')['default']
    MockMethodsList: typeof import('./components/mock/MockMethodsList.vue')['default']
    MockSceneItem: typeof import('./components/mock/MockSceneItem.vue')['default']
    PreviewFile: typeof import('./components/PreviewFile.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/layout/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    ToggleDark: typeof import('./components/ui/ToggleDark.vue')['default']
  }
}
