import type { JSONSchemaType } from 'ajv'
import type { Low } from 'lowdb'
import type { Mockery } from '../types'
import type { MockeryContext } from './context'
import type { MockeryConfigData, SceneData } from './schema'
import path from 'node:path'
import process from 'node:process'
import { consola, LogLevels } from 'consola'
import { colors } from 'consola/utils'
import fs from 'fs-extra'
import { JSONFilePreset } from 'lowdb/node'
import { getMockeryKey } from '../../packages/shared'
import { generateMockeryDTS } from './dts'
import { defaultConfigSchemaJSON, defaultSceneSchemaJSON } from './schema'
import { isMockery } from './utils'

/**
 * global state
 */
export class MockeryDB<T extends Record<string, any>> {
  /**
   * Server Start timestamp
   */
  startTimestamp = performance.now()

  sceneDBMap: Record<string, Low<SceneData>> = {}

  configDB?: Low<MockeryConfigData>
  configSchemaDB?: Low<JSONSchemaType<Partial<MockeryConfigData>>>
  /**
   * Current scene data
   */
  curSceneDB?: Low<SceneData>
  sceneSchemaDB?: Low<JSONSchemaType<Partial<SceneData>>>

  root = process.cwd()

  /**
   * auto generated by unplugin/ui
   *
   * - `.mockery/scenes/`: scene files
   * - `.mockery/schemas/`: schema file
   *   - `scene.schema.json`: scene schema file
   *   - `config.schema.json`: config schema file
   * - `.mockery/config.json`: configuration file
   */
  path: {
    /**
     * @default `.mockery`
     */
    dotMockeryDir: string
    /**
     * @default `.mockery/scenes`
     */
    sceneDir: string
    /**
     * @default `.mockery/schemas`
     */
    schemaDir: string
    /**
     * @default `.mockery/types`
     */
    typesDir: string
    /**
     * Configuration file
     * @default `.mockery/config.json`
     */
    configFile: string
    /**
     * @default `.mockery/schemas/config.schema.json`
     */
    configSchemaFile: string
    /**
     * Scene schema file
     * @default `.mockery/schemas/scene.schema.json`
     */
    sceneSchemaFile: string
    /**
     * dts for mockeryMap status
     * @default `mockery.d.ts`
     */
    mockeryTypeFile: string
  }

  constructor(public ctx: MockeryContext<T>) {
    this.path = this.getDotFilesPath('.mockery')
  }

  async init() {
    const dotFiles = this.ctx.options.dotFiles
    if (dotFiles) {
      if (typeof dotFiles === 'string') {
        this.path = this.getDotFilesPath(dotFiles)
      }
      await this.initDotFiles()
    }
  }

  /**
   * get dot files path
   *
   * `.mockery` directory
   * - `scenes/`: scene files
   * - `schemas/`: schema file
   * - `scene.schema.json`: scene schema file
   * - `config.schema.json`: config schema file
   * - `config.json`: configuration file
   * - `types/`: types files
   */
  getDotFilesPath(folder: string) {
    const dotMockeryDir = path.resolve(this.root, folder)

    return {
      dotMockeryDir,
      typesDir: path.resolve(dotMockeryDir, 'types'),
      sceneDir: path.resolve(dotMockeryDir, 'scenes'),
      schemaDir: path.resolve(dotMockeryDir, 'schemas'),

      configFile: path.resolve(dotMockeryDir, 'config.json'),
      configSchemaFile: path.resolve(dotMockeryDir, 'schemas/config.schema.json'),
      sceneSchemaFile: path.resolve(dotMockeryDir, 'schemas/scene.schema.json'),

      mockeryTypeFile: path.resolve(dotMockeryDir, 'mockery.d.ts'),
    }
  }

  /**
   * Initialize the configuration/schema file in the `.mockery` directory
   */
  async initDotFiles() {
    await Promise.all([
      fs.ensureDir(this.path.dotMockeryDir),
      fs.ensureDir(this.path.sceneDir),
      fs.ensureDir(this.path.schemaDir),

      (async () => {
        this.configDB = await JSONFilePreset<Partial<MockeryConfigData>>(this.path.configFile, {
          $schema: './schemas/config.schema.json',
          curScene: 'default',
        })
        await this.configDB.write()
      })(),
    ])

    await Promise.all([
      this.initSceneSchema(),
      this.initConfigSchema(),
    ])

    await this.readScene()
  }

  /**
   * 获取当前场景的路径
   */
  async getScenePath(sceneName?: string) {
    const curScene = sceneName || this.configDB?.data.curScene || 'default'
    const scenePath = path.resolve(this.path.sceneDir, `${curScene}.scene.json`)
    if (!await fs.exists(scenePath)) {
      const sceneStr = colors.magenta('SCENE')
      consola.info(`${sceneStr} file not found: ${colors.gray(scenePath)}`)
      this.curSceneDB = await JSONFilePreset<SceneData>(scenePath, {
        $schema: '../schemas/scene.schema.json',
      })
      await this.curSceneDB.write()
      consola.info(`Create ${sceneStr} file: ${colors.gray(scenePath)}`)
    }
    return scenePath
  }

  /**
   * Read scene data
   * @param sceneName
   */
  async readScene(sceneName: string = 'default') {
    this.curSceneDB = this.sceneDBMap[sceneName]

    if (!this.curSceneDB) {
      const scenePath = await this.getScenePath(sceneName)
      this.curSceneDB = await JSONFilePreset<SceneData>(scenePath, {
        $schema: './schemas/scene.schema.json',
      })
      this.sceneDBMap[sceneName] = this.curSceneDB
    }
    return this.curSceneDB
  }

  /**
   * Initialize types *.d.ts
   * mockery.d.ts
   */
  async initTypes() {
    const genDTSStart = performance.now()
    const dts = generateMockeryDTS(this.ctx.mockeryMap as MockeryContext['mockeryMap'])
    let mockeryTypeFile = this.path.mockeryTypeFile
    if (typeof this.ctx.options.dts === 'string') {
      mockeryTypeFile = path.resolve(this.root, this.ctx.options.dts)
    }

    await fs.ensureDir(path.dirname(mockeryTypeFile))
    await fs.writeFile(mockeryTypeFile, dts)

    const logLevel = this.ctx.options.logLevel || LogLevels.log
    if (logLevel >= LogLevels.debug) {
      const consumedTime = performance.now() - genDTSStart
      consola.success(`Generate ${colors.blue('dts')} in ${colors.green(`${consumedTime.toFixed(2)}ms`)}`)
    }
    return dts
  }

  /**
   * init `config.schema.json`
   */
  async initConfigSchema() {
    const scenes = await fs.readdir(this.path.sceneDir)
    const enumScenes = scenes.filter(i => i.endsWith('.scene.json')).map(i => i.replace('.scene.json', ''))
    defaultConfigSchemaJSON.properties.curScene.enum = Array.from((new Set(enumScenes)).add('default'))

    this.configSchemaDB = await JSONFilePreset<JSONSchemaType<Partial<MockeryConfigData>>>(this.path.configSchemaFile, defaultConfigSchemaJSON)
    await this.updateConfigSchema()
  }

  async initSceneSchema() {
    this.sceneSchemaDB = await JSONFilePreset<JSONSchemaType<Partial<SceneData>>>(this.path.sceneSchemaFile, defaultSceneSchemaJSON)
    this.ctx.state.filesMap.forEach((val) => {
      this.updateSceneSchema(val.mockery, {
        write: false,
      })
    })
    await this.sceneSchemaDB.write()
  }

  /**
   * Update scene schema
   * @param mockery
   */
  async updateSceneSchema(mockery: Mockery, options: {
    write: boolean
  } = {
    write: true,
  }) {
    if (!isMockery(mockery))
      return

    const mockeryKey = getMockeryKey(mockery)
    const propSchema: {
      type: string
      description?: string
      enum?: string[]
    } = {
      type: 'string',
      description: mockery.description,
    }

    if (JSON.stringify(this.sceneSchemaDB?.data.properties[mockeryKey]) !== JSON.stringify(propSchema)) {
      if (this.sceneSchemaDB) {
        this.sceneSchemaDB.data.properties[mockeryKey] = propSchema
        if (options.write) {
          await this.sceneSchemaDB?.write()
        }
      }
    }
  }

  async saveSceneSchema() {
    await this.sceneSchemaDB?.write()
  }

  async updateConfigSchema() {
    if (this.configSchemaDB) {
      const scenes = await fs.readdir(this.path.sceneDir)
      const enumScenes = scenes.filter(i => i.endsWith('.scene.json')).map(i => i.replace('.scene.json', ''))
      this.configSchemaDB.data.properties.curScene.enum = Array.from((new Set(enumScenes)).add('default'))
      await this.configSchemaDB.write()
      // empty line at the end of file
      await fs.appendFile(this.path.configSchemaFile, '\n')
    }
  }
}
