/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MockeryItem: typeof import('./components/mock/MockeryItem.vue')['default']
    MockeryList: typeof import('./components/mock/MockeryList.vue')['default']
    MockeryResultItem: typeof import('./components/mock/MockeryResultItem.vue')['default']
    MockFileItem: typeof import('./components/mock/MockFileItem.vue')['default']
    PreviewFile: typeof import('./components/PreviewFile.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectScene: typeof import('./components/SelectScene.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/layout/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    ToggleDark: typeof import('./components/ui/ToggleDark.vue')['default']
  }
}
